### ISSUE TITLE
Checkbox icons unconsistency

### ISSUE THREAD

**Issue by louim-lbs** [nextcloud/notes-android#1732]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Checkbox icons displayed for the notes preview in the main page differ from the checkbox in the view mode when editing a single note. Particularly, the "big red cross" is disturbing and do not fit the general theme. 

**To Reproduce**
1. Install notes... 

**Expected behavior**

The same white/grey icons as the editing mode. 

**Screenshots**

![SmartSelect_20230328_205303_Nextcloud Notes.jpg](https://user-images.githubusercontent.com/82395416/228340926-a3dfcc22-861b-4eab-a0a6-60edade4c08a.jpg)

![SmartSelect_20230328_205342_Nextcloud Notes.jpg](https://user-images.githubusercontent.com/82395416/228340950-97752f64-d775-4e3f-a0bd-0d0c713f3614.jpg)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.0.0
 - F-Droid or Play Store: Play Store
 - Android-Version: 13
 - Device: Samsung galaxy S20

**Server**
 - Nextcloud version: 26
 - Nextcloud Notes version (server app): I cannot check now. 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
The reason is quite simple and purely technical: Rendering markdown requires lots of resources and is very imperformant. Rendering markdown of all note contents in the card view leads to lacky scrolling and bad experience.

To not display `- [ ]` (which looks also pretty bad), we replace checkboxes with emojis in this scenario. Depending on the device and software, this might look good

![Screenshot_20230328-220314_Nextcloud Notizen](https://user-images.githubusercontent.com/4741199/228353970-0c0396c4-16e9-4475-92af-7797840097da.png)

or shitty (greetings to Samsung).

**Comment by louim-lbs** [comment]
Thank you for your explanation!

It makes sense and it definitely isn't a bug related to Notes. I think I just have to ask Samsung to change their icons then. And I'll close the issue. 

Beside, for my personal culture, is there any other way to render Markdown text without really using Markdown "engine" (I don't know how it works inside the black box), if it requires a lot of resources?
