### ISSUE TITLE
Nextcloud Notes for Android - Images are not displayed 

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/notes-android#1785]
In Notes in Nextcloud (access with Firefox browser on Win) it's possible to add images in Notes and it works. But in the Notes Android App these images are not displayed.

**Comment by demuxer86** [comment]
Same.  Really sucks.   Don't have a way to upload photos from Android either.   All works fine on desktop.

**Comment by stefan-niedermann** [comment]
Using the `Rich text editor` in the Notes Android app should display also images. Note, that this editor mode is only available on Nextcloud 26 and above.

Regarding the regular editor see https://github.com/nextcloud/notes-android/issues/1051

Closing this issue as duplicate.

>  Really sucks. 

Just as
- Deleting the issue template instrad of filling it
- Not searching for existing issues before opening new ones
- Commenting without any relevant information instead of using [GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)

**Comment by mario** [comment]
:p
